server:
  port: 8001
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  flyway:
    url: jdbc:mariadb://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: 1234
  sleuth:
    sampler:
      probability: 1.0
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs