version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
       - vidotto-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
       - vidotto-network

  naming-server:
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    environment:
      - EUREKA.CLIENT.REGISTERWITHEUREKA=false
      - EUREKA.CLIENT.FETCHREGISTRY=false
    ports:
      - "8761:8761"
    networks:
       - vidotto-network

  cambio-db:
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: docker
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: cambio_service
      MARIADB_ROOT_HOST: '%'
      TZ: America/Sao_Paulo
      MYSQL_TCP_PORT: 3308
    ports: 
      - 3308:3308
    expose:
      - 3308
    networks:
      - vidotto-network

  book-db:
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: docker
      MARIADB_PASSWORD: 1234
      MARIADB_DATABASE: book_service
      MARIADB_ROOT_HOST: '%'
      TZ: America/Sao_Paulo
      MYSQL_TCP_PORT: 3310
      MYSQL_UNIX_PORT: 3310
    ports: 
      - 3310:3310
    expose:
      - 3310
    networks:
      - vidotto-network

  api-gateway:
    image: docker.io/glasscode/api-gateway:V1
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - vidotto-network
    
  cambio-service:
    image: glasscode/cambio-service:V1
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.APPLICATION.NAME: cambio-service
      SPRING.DATASOURCE.DRIVER-CLASS-NAME: org.mariadb.jdbc.Driver
      SPRING.DATASOURCE.URL: jdbc:mariadb://cambio-db:3308/cambio_service?serverTimezone=UTC?createDatabaseIfNotExist=false #?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1234
      SPRING.FLYWAY.URL: jdbc:mariadb://cambio-db:3308/cambio_service?serverTimezone=UTC
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 1234
      SPRING.JPA.HIBERNATE.DDLAUTO: none
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports: 
      - 8001:8001
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
       - vidotto-network

  book-service:
    image: glasscode/book-service:V1
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mariadb://cambio-db:3308/cambio_service?serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1234
      SPRING.FLYWAY.URL: jdbc:mariadb://cambio-db:3308/cambio_service?serverTimezone=UTC
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 1234
      SPRING.JPA.HIBERNATE.DDLAUTO: none
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    networks:
      - vidotto-network

networks:
   vidotto-network:
     driver: bridge