server:
  port: 8100
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mariadb://localhost:3306/
    schemas: book_service
    user: root
    password: 1234
