name: Continuos Integration with Github

on:
#   schedule:
#     - cron: '28 0 * * *'
  push:
    branches: [ dockerizing ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ dockerizing ]

# env:
#   # Use docker.io for Docker Hub if empty
#   REGISTRY: ghcr.io
#   # github.repository as <account>/<repo>
#   IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Setup Java JDK
        uses: actions/setup-java@v3.1.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Eureka Naming Server container image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Eureka API Gateway container image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Cambio Microservice Jar
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests
        
      - name: Build Book Microservice Jar
        working-directory: ./book-service
        run: mvn clean package -DskipTests
        
      - name: Docker compose build
        working-directory: .
        run: docker-compose build

      - name: Push to Docker hub container registry
        run: |
          docker tag microservicesjava_naming-server:latest ${{secrets.DOCKER_USERNAME}}/naming-service:${{github.run_id}}
          docker tag microservicesjava_naming-server:latest ${{secrets.DOCKER_USERNAME}}/naming-service:latest
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:V1 ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:V1 ${{secrets.DOCKER_USERNAME}}/api-gateway:latest
          docker tag ${{secrets.DOCKER_USERNAME}}/cambio-service:V1 ${{secrets.DOCKER_USERNAME}}/cambio-service:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/cambio-service:V1 ${{secrets.DOCKER_USERNAME}}/cambio-service:latest
          docker tag ${{secrets.DOCKER_USERNAME}}/book-service:V1 ${{secrets.DOCKER_USERNAME}}/book-service:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/book-service:V1 ${{secrets.DOCKER_USERNAME}}/book-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/naming-service:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/naming-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:latest
          docker push ${{secrets.DOCKER_USERNAME}}/cambio-service:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/cambio-service:latest
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/book-service:latest
